<script src="//cdn.jsdelivr.net/phaser/2.4.8/phaser.min.js"></script>
<script>
var hautPage = (window.innerHeight - 17);
var largPage = (window.innerWidth - 17);
var game = new Phaser.Game(largPage, hautPage, Phaser.CANVAS, 'phaser-example', { preload: preload, create: create, update: update });

function preload() {
    game.load.image('banana', '<?php echo Mage::getDesign()->getSkinUrl("images/access/asset.png"); ?>');
    game.load.image('arrows', '<?php echo Mage::getDesign()->getSkinUrl("images/access/arrows.png"); ?>');
}

var k;

function create() {
    game.physics.startSystem(Phaser.Physics.ARCADE);
    game.stage.backgroundColor = '#fff';
    a = game.add.sprite(game.world.centerX, game.world.centerY, 'arrows');
    k = game.add.sprite(game.world.centerX, 2, 'banana');
    a.anchor.setTo(0.5, 2);
    k.anchor.setTo(0.5, 0.5);
    game.physics.enable(k, Phaser.Physics.ARCADE);
    //  This gets it moving
    k.body.velocity.setTo(200, 200);
    k.body.collideWorldBounds = true;
    k.body.bounce.set(0.85);
    k.body.gravity.set(0, 170);
}

function update() {
    if (game.input.keyboard.isDown(Phaser.Keyboard.LEFT)) {
        k.angle -= 4;
    } else if (game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)) {
        k.angle += 4;
    }

}
</script>
